### ISSUE TITLE
Make major release

### ISSUE THREAD

**Issue by fendor** [mpickering/hie-bios#88]
A lot has happened since the previous release and a new one might be sensible!

Issues that should be solved before a new release:

* [x] Fix Haddock. Some Documentation does not render properly. (@fendor, closed by #89)
* [x] Document changes and new features or make sure features are properly documented. #58 (@mpickering and @fendor) closed by #103
* [x] Regularise the API, #83 (@mpickering, supported by @fendor) Fixed in #87 
* [x] Don't use stdout to communicate arguments #90 (@mpickering)
* [x] Add project loading tests (@mpickering and @fendor) #91
* [x] Command `check` fails on hie-bios. #93 
* [x] Fix `fixImportDirs` #95
Issues that *could* be in the next release:
* [x] Parser fails when cabal runs configure in v2-repl #84 (Fixed in #90)

## Changes to the stack cradle before merge (EDITED: 26.11.2019)

* [x] Call `--compiler-exe` before running `stack repl`
* [x] By default don't pass a path to `stack repl`
* [x] Add an optional component like the `cabal` cradle
* [x] Do some simple parsing of the ghci script file to find the initial targets

## Final touch

* [x] Updating the README (it promostes a cradle: `cradle: { stack }` which no longer works) (@fendor) #103
* [x] Decrease the cabal-version. (@fendor) #103

**Comment by mpickering** [comment]
@fendor Do you want me to deal with all these subtasks?

**Comment by fendor** [comment]
No, I would like to take on the haddock tasks, and help with documentation.

**Comment by mpickering** [comment]
Project loading tests in #91

**Comment by mpickering** [comment]
The only task left here seems to be the documentation checking.

**Comment by fendor** [comment]
Updates task list!

**Comment by mpickering** [comment]
I made #96 for the changes to the stack cradle as well.

**Comment by mpickering** [comment]
All these tasks are complete, so we are ready to do a release?

**Comment by fendor** [comment]
Two last tasks:
* [ ] Updating the README (it promostes a cradle: `cradle: { stack }` which no longer works) (@fendor)
* [ ] Decrease the cabal-version. (@fendor)
